/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReflectRouteImport } from './routes/reflect'
import { Route as BibleRouteImport } from './routes/bible'
import { Route as IndexRouteImport } from './routes/index'

const ReflectRoute = ReflectRouteImport.update({
  id: '/reflect',
  path: '/reflect',
  getParentRoute: () => rootRouteImport,
} as any)
const BibleRoute = BibleRouteImport.update({
  id: '/bible',
  path: '/bible',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bible': typeof BibleRoute
  '/reflect': typeof ReflectRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bible': typeof BibleRoute
  '/reflect': typeof ReflectRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bible': typeof BibleRoute
  '/reflect': typeof ReflectRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/bible' | '/reflect'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/bible' | '/reflect'
  id: '__root__' | '/' | '/bible' | '/reflect'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BibleRoute: typeof BibleRoute
  ReflectRoute: typeof ReflectRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reflect': {
      id: '/reflect'
      path: '/reflect'
      fullPath: '/reflect'
      preLoaderRoute: typeof ReflectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bible': {
      id: '/bible'
      path: '/bible'
      fullPath: '/bible'
      preLoaderRoute: typeof BibleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BibleRoute: BibleRoute,
  ReflectRoute: ReflectRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
